version: '2'

services:
  web:
   container_name: node-app-web
   build: .
   restart: always
   environment:
     - VIRTUAL_HOST=app.vlogz.win
     - LETSENCRYPT_HOST=app.vlogz.win
     - LETSENCRYPT_EMAIL=webmaster@vlogz.win
   volumes:
     - .:/home/app-user/app
     - /home/app-user/app/node_modules
